apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-test
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-test
  template:
    metadata:
      labels:
        app: speedtest-test
    spec:
      containers:
        - name: speedtest-node
          image: hermanho/speedtest-node:latest
          # imagePullPolicy: Always
          ports:
          - containerPort: 8888
            protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          # command: ["node"]
          # args: ["--inspect-brk=0.0.0.0", "src/SpeedTest.js"]
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-test-clusterip
  namespace: speedtest
  labels:
    app: speedtest-test
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: speedtest-test
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: speedtest-test
---